name: site

on:
  pull_request:
    paths:
      - 'site/**'
    branches:
      - main
  push:
    paths:
      - 'site/**'
    branches:
      - main

jobs:
  manifest:
    name: test manifest/install script changes
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install script
        run: cat site/install.sh | bash
      
      - name: add gemtesh cli to PATH
        run: test -f "${HOME}/.getmesh/bin/getmesh" && echo "${HOME}/.getmesh/bin" >> $GITHUB_PATH

      - name: download all the istioctl
        run: |
          cat site/manifest.json | jq -r '.istio_distributions[] | [.version, .flavor, .flavor_version] | @csv' | tr -d '"' | 
          while IFS=, read -r version flavor flavor_version; do
              getmesh fetch --version $version --flavor $flavor --flavor-version $flavor_version
          done
