name: build-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  license:
    name: license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: addlicense
        run: go get github.com/google/addlicense

      - name: checkout
        uses: actions/checkout@v2

      - name: gen license headers
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make license

      - name: check diff
        run: git diff --exit-code

  doc-gen:
    name: doc gen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: gen doc
        run: make doc-gen

      - name: check diff
        run: git diff --exit-code

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: -v

  unittests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest]
    name: unittests
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: download dependencies
        run: go mod download

      - name: run
        run: make test

      - name: build
        run: go build .

  e2e-test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    name: e2e test
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'v1.21.2-k3s1'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: build
        run: go build .

      - name: e2e
        run: |
          make e2e-test
